### ISSUE TITLE
Made some optimizations in utils.c code

### ISSUE THREAD

**Issue by Samson666** [sk-io/os#2]
I added some optimization #pragmas and changed memcpy in an assembler version.
I think it made the graphic operations significant faster and i get less tearing than before.
The optimization is done locally because if you switch on optimization globally i get a page fault.

https://github.com/Samson666/QuadOS/commit/87e137f141ac4a256d2578cab9ea00cd52e06118#diff-d46dec90a1e8611395fdffcbb44dd1342e21ff1f305a24af4b221a3451730936

**Comment by sk-io** [comment]
That's nice. For this project, I'm not super focused on optimizing it yet, as long as it's not too slow to be usable. Another optimization idea would be to only redraw the parts of the screen that actually change. Since this is all software rendered, that's going to have a big impact I think.

Eventually I want to try to implement some kinda system wide profiler. But since a lot of kernel code disables interrupts I don't know useful that will be for optimizing the kernel side.

**Comment by Samson666** [comment]
Yeah, i thought about "dirty" rectangles too.

I'm just working on resizing windows. It works so far, but it took me a bunch of time to understand how the memory for the framebuffer is allocated and mapped. 
One thing i'm curios about is, why do i have to map the fb memory to the kernel first and later on to the current task. If i map it to the current task in the beginning, the kernel throws a page fault :thinking: 

In the first place, i tried to resize the sharedmem object, but it was a mess.
Eventually i came up to destroy the object and create a new one. Maybe there is a better to achieve this.

Now i wanna add a resize grip :-)
